/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * 
 *
 * Created on 29-abr-2009, 10:59:33
 */

package agendainteligente;

import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author Marc Sitges
 */
public class VistaModificarAniversario extends javax.swing.JDialog {

    CtrlDominio3 CD3 = new CtrlDominio3();
    CtrlCrearActividad2 CCA = new CtrlCrearActividad2();
    CtrlEliminarActividad CEA = new CtrlEliminarActividad();
    int idActividadSeleccionada;
    boolean existe = false;
    /** Creates new form VistaModificarAniversario
     * @param parent
     * @param modal
     * @param idAct
     */
    public VistaModificarAniversario(java.awt.Frame parent, boolean modal, int idAct) {
        super(parent, modal);
        initComponents();
        jLabel1.setText("");
        jLabel3.setText("");
        idActividadSeleccionada = idAct;
        existe = cargarAniversario(idActividadSeleccionada);
        if(!existe)jLabel1.setText("No hay ningun aniversario en el sistema");
    }

     private boolean cargarAniversario(int idActividadSeleccionada) {

        Actividad a=CD3.CA3.buscarActividad(idActividadSeleccionada);
        if(a==null){
            fecha.disable();
            campoNombre.disable();
            return false;
        }
        Aniversario modificador=(Aniversario)a;

        campoNombre.setText(modificador.getTitulo());
        campoNombre.disable();
        Calendar c = Calendar.getInstance();
        c.setTime(modificador.getFechaNacimiento());
        fecha.setSelectedDate(c);
        return true;

    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fecha = new datechooser.beans.DateChooserCombo();
        modificarAniversario = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel7.setText("Fecha de nacimiento");

        jLabel2.setText("Nombre");

        fecha.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
            public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
                fechaOnSelectionChange(evt);
            }
        });

        modificarAniversario.setText("Modificar");
        modificarAniversario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarAniversarioActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel10.setText("Modificar Aniversario");

        campoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoNombreKeyTyped(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("jLabel3");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(134, 134, 134)
                .add(modificarAniversario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 89, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(45, 45, 45)
                .add(jButton2)
                .addContainerGap(192, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(168, 168, 168)
                .add(jLabel10)
                .addContainerGap(224, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(31, 31, 31)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(jLabel7))
                .add(24, 24, 24)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel3)
                    .add(jLabel1)
                    .add(fecha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(campoNombre, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(227, 227, 227))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(jLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(30, 30, 30)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(campoNombre, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(25, 25, 25)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel7)
                    .add(fecha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 31, Short.MAX_VALUE)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton2)
                    .add(modificarAniversario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarAniversarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarAniversarioActionPerformed
        // TODO add your handling code here:
        if(!existe) jLabel1.setText("Aniversario inexsitente");
        else{
            String nombre = campoNombre.getText();
            Calendar Fecha;
            Date data;
            Date actual = new Date();
            Fecha = fecha.getCurrent();
            data = Fecha.getTime();

            if(nombre.isEmpty()){
                if(data.after(actual)){
                    jLabel1.setText("El campo nombre esta vacio");
                    jLabel3.setText("y la fecha es posterior a la actual");
                }
                else jLabel1.setText("El campo nombre esta vacio");
            }
            else if(data.after(actual)){
                   jLabel1.setText("La fecha es posterior a la actual");
            }
            else {
                CEA.eliminarActividadTodo(idActividadSeleccionada);
                idActividadSeleccionada = CCA.crearActividad(nombre, "", "Aniversario");
                CD3.completarAniversario(idActividadSeleccionada, data);
                this.dispose();
            }
        }
}//GEN-LAST:event_modificarAniversarioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fechaOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_fechaOnSelectionChange
        // TODO add your handling code here:
        jLabel1.setText("");
        jLabel3.setText("");
    }//GEN-LAST:event_fechaOnSelectionChange

    private void campoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNombreKeyTyped
        // TODO add your handling code here:
        jLabel1.setText("");
        jLabel3.setText("");
    }//GEN-LAST:event_campoNombreKeyTyped

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            private int idActividad;
            public void run() {
                VistaModificarAniversario dialog = new VistaModificarAniversario(new javax.swing.JFrame(), true, idActividad);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoNombre;
    private datechooser.beans.DateChooserCombo fecha;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton modificarAniversario;
    // End of variables declaration//GEN-END:variables

}
