/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VistaAnadirEnMente.java
 *
 * Created on 29-abr-2009, 20:16:54
 */

package agendainteligente;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;


/**
 *
 * @author Marc Sitges
 */
public class VistaAnadirEnMente extends javax.swing.JDialog {

    /** Creates new form VistaAnadirEnMente */
    CtrlAgenda CDA = new CtrlAgenda();
    CtrlCrearTema CT = new CtrlCrearTema();
    CtrlEliminarActividad CEA = new CtrlEliminarActividad();
    CtrlCrearActividad2 nuevaEnMente= new CtrlCrearActividad2();

    /**
     *
     * @param parent
     * @param modal
     */
    public VistaAnadirEnMente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarTemas();
        textoError.setText("");
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */


    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TextoHoras = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        comboTema = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        Aceptar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        NuevoTema = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        textoError = new javax.swing.JLabel();
        fechaCombo = new datechooser.beans.DateChooserCombo();
        FechaInicio = new javax.swing.JLabel();
        horasMin = new javax.swing.JFormattedTextField();
        horasMax = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Añadir: En mente");

        jLabel2.setText("Titulo");

        jLabel5.setText("Tema");

        jLabel6.setText("Num. Horas");

        jLabel4.setText("Prioridad");

        TextoHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoHorasActionPerformed(evt);
            }
        });
        TextoHoras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextoHorasKeyTyped(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alta", "Media", "Baja" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        comboTema.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ninguno"}));
        comboTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTemaActionPerformed(evt);
            }
        });

        jLabel3.setText("Descripcion");

        jScrollPane2.setViewportView(jTextPane1);

        Aceptar.setText("Ok");
        Aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AceptarMouseClicked(evt);
            }
        });
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelarMouseExited(evt);
            }
        });

        NuevoTema.setText("Nuevo Tema");
        NuevoTema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NuevoTemaMouseClicked(evt);
            }
        });
        NuevoTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoTemaActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Laboral");

        textoError.setForeground(new java.awt.Color(255, 0, 0));
        textoError.setText("jLabel7");

        FechaInicio.setText("Fecha Inicio");

        try {
            horasMin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        horasMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                horasMinKeyTyped(evt);
            }
        });

        try {
            horasMax.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        horasMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horasMaxActionPerformed(evt);
            }
        });
        horasMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                horasMaxKeyTyped(evt);
            }
        });

        jLabel7.setText("Numero de horas como minimo");

        jLabel8.setText("Numero de horas como maximo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextoHoras)
                                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboTema, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(NuevoTema))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(48, 48, 48)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(textoError))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Cancelar)))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(horasMax, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(horasMin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(FechaInicio))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fechaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(fechaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(comboTema, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NuevoTema))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(TextoHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox1))
                            .addComponent(FechaInicio))))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(horasMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(horasMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cancelar)
                            .addComponent(Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(textoError)))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jComboBox3ActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_AceptarActionPerformed

    private void comboTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTemaActionPerformed
        // TODO add your handling code here:
        textoError.setText("");
}//GEN-LAST:event_comboTemaActionPerformed

    private void AceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AceptarMouseClicked
        // TODO add your handling code here:
        boolean error1=false;
        boolean error2=false;
        boolean error3=false;
        boolean error4=false;
        boolean error5=false;

        int slotMin = 1;
        int slotMax = 1;
        Date inicio;

        textoError.setText("");
        String titulo = jTextField1.getText();  //captura el titulo
        String tema = (String) comboTema.getSelectedItem(); //captura el tema
        if(tema.equals("Ninguno"))error5=true;
        String prioridad = (String) jComboBox3.getSelectedItem();
        String descripcion = jTextPane1.getText();
        String horas = TextoHoras.getText();
        boolean laboral=jCheckBox1.isSelected();
        Calendar c = null;
        c = fechaCombo.getSelectedDate();
        inicio = c.getTime();

        String prueba = horasMin.getText();
        try{
            slotMin = Integer.parseInt(prueba);
        }catch(Exception e){
            slotMin=0;          
        }
        prueba = horasMax.getText();
        try{
            slotMax = Integer.parseInt(prueba);
        }catch(Exception e){
            slotMax=0;          
        }

        if(slotMax<slotMin) error1=true;
        
        int h=0;
        int prio;
        int resultat = 1;
        if(prioridad.equals("Alta")) prio=Constantes.Alta;
        else if(prioridad.equals("Media")) prio = Constantes.Media;
        else prio = Constantes.Baja;

        try{
            h = Integer.parseInt(horas);
        }catch(Exception e){
            h=0;           
        }

        if(titulo.isEmpty())error2=true;
        if(tema == null)error3=true;
        if(descripcion.isEmpty())error4=true;

        if(!error1 && !error2 && !error3 && !error4 && !error5){

            int idActividad = nuevaEnMente.crearActividad(titulo, descripcion, "EnMente");
            CT.crearTema(tema, titulo, idActividad);

            /*Si la creacion ha tenido exito*/
            if(idActividad>0){
                /*Si horas es superior a 0*/
                if(h>0){
                    Calendar cal = Calendar.getInstance();
                    cal.setTime (inicio);
                    cal.add (Calendar.YEAR, 1);
                    Date fin= cal.getTime();
                    nuevaEnMente.completarEnMente(prio, h, laboral, slotMin, slotMax, inicio);

                    while(resultat!=0){

                        resultat=CDA.asignacionAutomatica(idActividad, prio, h, laboral,
                            inicio, fin, slotMin, slotMax);

                        if(resultat>0){

                            inicio= (Date) CtrlAgenda.diaSiguiente(fin).clone();
                            fin = CtrlAgenda.annoSiguiente(inicio);
                            h=resultat;
                        }
                    }
                    this.dispose();
                }
                else{
                    Date fin = (Date) CDA.annoSiguiente(inicio).clone();
                    nuevaEnMente.completarEnMente(prio, h, laboral, 0, 0,inicio);
                    CtrlCrearAviso CCA = new CtrlCrearAviso();
                    while(inicio.before(fin)){
                       int idAv=CCA.crearAviso(inicio, idActividad);
                        inicio = (Date) CDA.semanaSiguiente(inicio).clone();
                    }
                    this.dispose();
                }
            }
        }
        else{
            if(error1)textoError.setText("Error en las horas minimos y maximas");
            else if(error2)textoError.setText("titulo inexistente");
            else if(error3)textoError.setText("el tema es nulo");
            else if(error4)textoError.setText("no existe descripcion");
            else if(error5)textoError.setText("selecciona un tema");
        }

        
       
}//GEN-LAST:event_AceptarMouseClicked

    private void CancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarMouseExited
        // TODO add your handling code here:
}//GEN-LAST:event_CancelarMouseExited

    private void NuevoTemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NuevoTemaMouseClicked
        // TODO add your handling code here:
        VistaCrearTema nuevoTema = new VistaCrearTema(new javax.swing.JFrame(), true);
        nuevoTema.setVisible(true);
        comboTema.removeAllItems();
        cargarTemas();
        

}//GEN-LAST:event_NuevoTemaMouseClicked

    private void CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarMouseClicked
        // TODO add your handling code here:
        //this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_CancelarMouseClicked

    private void NuevoTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoTemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoTemaActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        textoError.setText("");
    }//GEN-LAST:event_jTextField1KeyTyped

    private void TextoHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoHorasActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_TextoHorasActionPerformed

    private void horasMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horasMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horasMaxActionPerformed

    private void TextoHorasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextoHorasKeyTyped
        // TODO add your handling code here:
        textoError.setText("");
    }//GEN-LAST:event_TextoHorasKeyTyped

    private void horasMinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_horasMinKeyTyped
        // TODO add your handling code here:
        textoError.setText("");
    }//GEN-LAST:event_horasMinKeyTyped

    private void horasMaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_horasMaxKeyTyped
        // TODO add your handling code here:
        textoError.setText("");
    }//GEN-LAST:event_horasMaxKeyTyped
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            private Date inicio;
            public void run() {
                VistaAnadirEnMente dialog = new VistaAnadirEnMente(new javax.swing.JFrame(), true/*, inicio*/);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private  void cargarTemas(){

        ArrayList<String>lista=CDA.listartemas();
        int indiceI=0;
        int tamanyo=lista.size();
        while(indiceI<tamanyo){
               comboTema.addItem(lista.get(indiceI));
             indiceI++;
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel FechaInicio;
    private javax.swing.JButton NuevoTema;
    private javax.swing.JTextField TextoHoras;
    private javax.swing.JComboBox comboTema;
    private datechooser.beans.DateChooserCombo fechaCombo;
    private javax.swing.JFormattedTextField horasMax;
    private javax.swing.JFormattedTextField horasMin;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel textoError;
    // End of variables declaration//GEN-END:variables

}
