/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VistaGestionJornada.java
 *
 * Created on 29-abr-2009, 20:39:36
 */

package agendainteligente;

/**
 *
 * @author Marc Sitges
 */
public class VistaGestionJornada extends javax.swing.JDialog {

    CtrlDominio3 CD3;
    JornadaLaboral JL;
    /** Creates new form VistaGestionJornada
     * @param parent
     * @param modal
     */
    public VistaGestionJornada(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        CD3 = new CtrlDominio3();
        JL = new JornadaLaboral();
        textoErrorLaboral.setText("");
        textoErrorOcio.setText("");
        textoErrorLaboral2.setText("");
        textoErrorOcio2.setText("");
        cargarHoras();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        BotonOk = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        textoErrorOcio = new javax.swing.JLabel();
        textoErrorLaboral = new javax.swing.JLabel();
        textoErrorOcio2 = new javax.swing.JLabel();
        textoErrorLaboral2 = new javax.swing.JLabel();
        HIL = new javax.swing.JComboBox();
        HFL = new javax.swing.JComboBox();
        HIO = new javax.swing.JComboBox();
        HFO = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion Jornada");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Gestion Jornadas");

        jLabel2.setText("Hora inicio");

        jLabel3.setText("Hora final");

        jLabel4.setText("Hora inicio");

        jLabel5.setText("Hora final");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setText("Horario laboral");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setText("Horario de ocio");

        BotonOk.setText("Ok");
        BotonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonOkActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("h.");

        jLabel10.setText("h.");

        jLabel11.setText("h.");

        jLabel12.setText("h.");

        textoErrorOcio.setForeground(new java.awt.Color(255, 0, 0));
        textoErrorOcio.setText("jLabel9");

        textoErrorLaboral.setForeground(new java.awt.Color(255, 0, 0));
        textoErrorLaboral.setText("jLabel13");

        textoErrorOcio2.setForeground(new java.awt.Color(255, 0, 0));
        textoErrorOcio2.setText("jLabel9");

        textoErrorLaboral2.setForeground(new java.awt.Color(255, 0, 0));
        textoErrorLaboral2.setText("jLabel13");

        HIL.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3","4", "5", "6", "7","8", "9", "10", "11","12", "13", "14", "15","16", "17", "18", "19","20", "21", "22", "23" }));

        HFL.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3","4", "5", "6", "7","8", "9", "10", "11","12", "13", "14", "15","16", "17", "18", "19","20", "21", "22", "23" }));

        HIO.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3","4", "5", "6", "7","8", "9", "10", "11","12", "13", "14", "15","16", "17", "18", "19","20", "21", "22", "23"}));

        HFO.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3","4", "5", "6", "7","8", "9", "10", "11","12", "13", "14", "15","16", "17", "18", "19","20", "21", "22", "23" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(HIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(HFO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12))
                                    .addGap(35, 35, 35)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textoErrorOcio2)
                                        .addComponent(textoErrorOcio)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                    .addComponent(BotonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton1)))
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(HIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HFL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(39, 39, 39)
                                        .addComponent(textoErrorLaboral))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(39, 39, 39)
                                        .addComponent(textoErrorLaboral2))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(textoErrorLaboral)
                    .addComponent(HIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10)
                    .addComponent(textoErrorLaboral2)
                    .addComponent(HFL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel11)
                            .addComponent(textoErrorOcio)
                            .addComponent(HIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12)
                            .addComponent(textoErrorOcio2)
                            .addComponent(HFO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BotonOk)
                        .addComponent(jButton1)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonOkActionPerformed
        // TODO add your handling code here:
        String hInicioLaboral = (String) HIL.getSelectedItem();
        String hFinLaboral = (String) HFL.getSelectedItem();
        String hInicioOcio = (String) HIO.getSelectedItem();
        String hFinOcio = (String) HFO.getSelectedItem();

        int hInicioLabo = Integer.parseInt(hInicioLaboral);
        int hFinLabo = Integer.parseInt(hFinLaboral);
        int hInicioO = Integer.parseInt(hInicioOcio);
        int hFinO = Integer.parseInt(hFinOcio);

        boolean correcto = comprobarValores(hInicioLabo, hFinLabo, hInicioO, hFinO);

        if(!correcto) System.out.println("Error de formato");
        else {
            CD3.modificarGestionJornada(hInicioLabo, hFinLabo, hInicioO, hFinO );
            this.dispose();
        }
    }//GEN-LAST:event_BotonOkActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VistaGestionJornada dialog = new VistaGestionJornada(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    /**
     *
     */
    public void cargarHoras(){

        HIL.setSelectedIndex(JL.getHoraInicioJornadaLaboral());
        HFL.setSelectedIndex(JL.getHoraFinJornadaLaboral());
        HIO.setSelectedIndex(JL.getHoraInicioJornadaOcio());
        HFO.setSelectedIndex(JL.getHoraFinJornadaOcio());

    }
    /**
     *
     * @param hInicioLabo
     * @param hFinLabo
     * @param hInicioLuc
     * @param hFinLuc
     * @return
     */
    public boolean comprobarValores(int hInicioLabo, int hFinLabo, int hInicioLuc, int hFinLuc){

        boolean correcte =false;
        boolean error1 = false;
        boolean error2 = false;
        boolean error3 = false;
        boolean error4 = false;
        boolean error5 = false;
        boolean error6 = false;

        textoErrorLaboral.setText("");
        textoErrorOcio.setText("");
        textoErrorLaboral2.setText("");
        textoErrorOcio2.setText("");

        if(!((hInicioLabo < hFinLabo) && (hInicioLuc < hFinLuc)))error1=true;
        if(!((hFinLabo<=hInicioLuc)||(hFinLuc<=hInicioLabo)))error2=true;
        if(!((0<=hFinLabo) && (hFinLabo<24)))error3=true;
        if(!((0<=hInicioLabo) && (hInicioLabo<24)))error4=true;
        if(!((0<=hInicioLuc) && (hInicioLuc<24)))error5=true;
        if(!((0<=hFinLuc) &&(hFinLuc<24)))error6=true;

        if(!error1 && !error2 && !error3 && !error4 && !error5 && !error6)correcte=true;
        
        if(error6) textoErrorOcio2.setText("Hora fin ocio incorrecta");
        if(error5) textoErrorOcio.setText("Hora inicio ocio incorrecta");
        if(error4) textoErrorLaboral.setText("Hora inicio laboral incorrecta");
        if(error3) textoErrorLaboral2.setText("Hora fin laboral incorrecta");
        if(error2) textoErrorLaboral.setText("Horarios laboral y de ocio solapados");
        if(error1) textoErrorLaboral.setText("Error de formato");
        return correcte;
    }//fin operacion

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonOk;
    private javax.swing.JComboBox HFL;
    private javax.swing.JComboBox HFO;
    private javax.swing.JComboBox HIL;
    private javax.swing.JComboBox HIO;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel textoErrorLaboral;
    private javax.swing.JLabel textoErrorLaboral2;
    private javax.swing.JLabel textoErrorOcio;
    private javax.swing.JLabel textoErrorOcio2;
    // End of variables declaration//GEN-END:variables

}
