/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/* Descripcion: Muestra una actividad seleccionada por pantalla, interactua con
 * CtrlDominio3
 * VistaVerCita.java
 * Autor Carlos Vivas
 * Created on 24-may-2009, 20:50:10
 */

package agendainteligente;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;

public class VistaVerCita extends javax.swing.JDialog {

    CtrlAgenda CAGE= new CtrlAgenda();
    CtrlDominio3 control =  new CtrlDominio3();
    int id;
    Date fecha;

    public VistaVerCita(java.awt.Frame parent, boolean modal,int id,Date fecha) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.id=id;
        this.fecha=fecha;
        cargarTemas();
        inicializarCampos();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextPane();
        comboFecha = new datechooser.beans.DateChooserCombo();
        checkLaboral = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        formatTextHf = new javax.swing.JFormattedTextField();
        formatTextHi = new javax.swing.JFormattedTextField();
        boxPeriodicidad = new javax.swing.JComboBox();
        checkRepetitiva = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        boxTema = new javax.swing.JComboBox();
        checkAviso = new javax.swing.JCheckBox();
        comboFFin = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel7.setText("Fecha");

        jLabel2.setText("Titulo");

        txtTitulo.setEnabled(false);

        jLabel5.setText("Descripcion");

        txtDescripcion.setEnabled(false);
        jScrollPane2.setViewportView(txtDescripcion);

        comboFecha.setEnabled(false);

        checkLaboral.setText("Es laboral");
        checkLaboral.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Vista Cita");

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Hora inicio");

        jLabel8.setText("Hora fin");

        formatTextHf.setEnabled(false);

        formatTextHi.setEnabled(false);

        boxPeriodicidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ninguna", "Diaria", "Semanal", "Mensual", "Anual" }));
        boxPeriodicidad.setToolTipText("indique la periodicidad");
        boxPeriodicidad.setEnabled(false);
        boxPeriodicidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxPeriodicidadActionPerformed(evt);
            }
        });

        checkRepetitiva.setText("Repetitiva");
        checkRepetitiva.setEnabled(false);

        jLabel3.setText("Tema");

        boxTema.setModel(new javax.swing.DefaultComboBoxModel());
        boxTema.setEnabled(false);

        checkAviso.setText("Aviso");
        checkAviso.setEnabled(false);

        comboFFin.setEnabled(false);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(10, 10, 10)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel7)
                                            .add(jLabel2)
                                            .add(checkLaboral)
                                            .add(jLabel3))
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(layout.createSequentialGroup()
                                                .add(18, 18, 18)
                                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                                    .add(layout.createSequentialGroup()
                                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                            .add(jLabel6)
                                                            .add(jLabel8))
                                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                                            .add(formatTextHf, 0, 0, Short.MAX_VALUE)
                                                            .add(formatTextHi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                                    .add(layout.createSequentialGroup()
                                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                                            .add(boxTema, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .add(txtTitulo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                                                        .add(124, 124, 124)
                                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                            .add(comboFFin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                            .add(layout.createSequentialGroup()
                                                                .add(jLabel5)
                                                                .add(33, 33, 33)
                                                                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 133, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))))
                                            .add(comboFecha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                    .add(layout.createSequentialGroup()
                                        .add(checkRepetitiva)
                                        .add(25, 25, 25)
                                        .add(boxPeriodicidad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 168, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(checkAviso)))
                            .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE))
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(39, 39, 39))))
            .add(layout.createSequentialGroup()
                .add(257, 257, 257)
                .add(jLabel1)
                .addContainerGap(290, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(11, 11, 11)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(32, 32, 32)
                                .add(jLabel5))
                            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(25, 25, 25)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtTitulo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel2))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel3)
                            .add(boxTema, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(32, 32, 32)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel7)
                            .add(comboFecha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(89, 89, 89)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(boxPeriodicidad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(checkRepetitiva)))
                    .add(layout.createSequentialGroup()
                        .add(59, 59, 59)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(formatTextHi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel6))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(26, 26, 26)
                                .add(formatTextHf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel8)
                                    .add(checkLaboral))))
                        .add(18, 18, 18)
                        .add(comboFFin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(18, 18, 18)
                .add(checkAviso)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 14, Short.MAX_VALUE)
                .add(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
}//GEN-LAST:event_jButton1ActionPerformed

    private void boxPeriodicidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxPeriodicidadActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_boxPeriodicidadActionPerformed

    //Carga los datos de la actividad
    private void inicializarCampos(){
        Actividad ci=control.CA3.buscarActividad(id);
        Cita mostrador=(Cita)ci;
        Calendar c= Calendar.getInstance();
        comboFFin.setVisible(false);

        txtTitulo.setText(mostrador.getTitulo());
        txtDescripcion.setText(mostrador.getDescripcion());
        checkLaboral.setSelected(mostrador.isEsLaboral());
        ArrayList<TCtrlHorSlot> listaH = CAGE.obtenerSlotsDeActividadConFecha(id,fecha);
        TCtrlHorSlot primero = listaH.get(0);
        TCtrlHorSlot ultimo = listaH.get(listaH.size()-1);
        formatTextHi.setText(String.valueOf(primero.slot));
        formatTextHf.setText(String.valueOf((ultimo.slot)+1));
        c.setTime(fecha);
        comboFecha.setSelectedDate(c);
        checkRepetitiva.setSelected(mostrador.isRepetitiva());
        boxTema.setSelectedItem(control.obtenerTema(id));

        ArrayList<Integer>aviso=control.CA3.obtenerAvisos(id);
        if(!aviso.isEmpty()){
         checkAviso.setSelected(true);
        }
        else{
            checkAviso.setSelected(false);
        }

        if(mostrador.isRepetitiva()){
            CitaRepetitiva m=(CitaRepetitiva)ci;
            boxPeriodicidad.setSelectedIndex(m.getPeriodicidad());
            comboFFin.setVisible(true);
            c.setTime(m.getFinPeriodicidad());
            comboFFin.setSelectedDate(c);
        }
    }

    //carga los temas en el boxTema
    private  void cargarTemas(){

        ArrayList<String>lista=control.listartemas();
        int indiceI=0;
        int tamanyo=lista.size();
        boxTema.addItem(Constantes.NINGUNO);
        while(indiceI<tamanyo){
               boxTema.addItem(lista.get(indiceI));
             indiceI++;
        }

    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            int idAct;
            Date fecha;
            public void run() {
                VistaVerCita dialog = new VistaVerCita(new javax.swing.JFrame(), true,idAct, fecha);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox boxPeriodicidad;
    protected javax.swing.JComboBox boxTema;
    private javax.swing.JCheckBox checkAviso;
    private javax.swing.JCheckBox checkLaboral;
    private javax.swing.JCheckBox checkRepetitiva;
    private datechooser.beans.DateChooserCombo comboFFin;
    private datechooser.beans.DateChooserCombo comboFecha;
    private javax.swing.JFormattedTextField formatTextHf;
    private javax.swing.JFormattedTextField formatTextHi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextPane txtDescripcion;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

}
