/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VistaSemanaEvento.java
 *
 * Created on 18-may-2009, 2:31:59
 */

package agendainteligente;

import java.util.Date;

/**
 *
 * @author Carlos Vivas Abilahoud 
 */
public class VistaSemanaEvento extends javax.swing.JPanel {
    Date fechaInicioSemana = new Date();
    CtrlDominio3 CD3 = new CtrlDominio3();
    /** Creates new form VistaSemanaEvento */
    public VistaSemanaEvento() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHorarios = new javax.swing.JTable();

        tablaHorarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaHorarios.setCellSelectionEnabled(true);
        tablaHorarios.setColumnSelectionAllowed(true);
        tablaHorarios.setRowHeight(34);
        tablaHorarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaHorarios.getTableHeader().setReorderingAllowed(false);
        tablaHorarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaHorariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaHorarios);
        tablaHorarios.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaHorarios.getColumnModel().getColumn(0).setResizable(false);
        tablaHorarios.getColumnModel().getColumn(1).setResizable(false);
        tablaHorarios.getColumnModel().getColumn(2).setResizable(false);
        tablaHorarios.getColumnModel().getColumn(3).setResizable(false);
        tablaHorarios.getColumnModel().getColumn(4).setResizable(false);
        tablaHorarios.getColumnModel().getColumn(5).setResizable(false);
        tablaHorarios.getColumnModel().getColumn(6).setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 689, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tablaHorariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaHorariosMouseClicked
        int columna,fila;
        columna = this.tablaHorarios.getSelectedColumn();
        fila= this.tablaHorarios.getSelectedRow();

        Date fechaActual = CD3.obtenerFechaDiaSeleccionado(this.fechaInicioSemana, columna+1);
        int id=CD3.obtenerIdActividad(fila, columna, CD3.getSemanaEvento());
        VistaGestionActividad d = new VistaGestionActividad(new javax.swing.JFrame(),true,id,fechaActual);
           d.setVisible(true);
    }//GEN-LAST:event_tablaHorariosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tablaHorarios;
    // End of variables declaration//GEN-END:variables

}
