/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/* Descripcion: Muestra una actividad seleccionada por pantalla, interactua con
 * CtrlDominio3
 * VistaVerEnMente.java
 * Autor: Carlos Vivas
 * Created on 24-may-2009, 22:19:29
 */

package agendainteligente;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;


public class VistaVerEnMente extends javax.swing.JDialog {

    CtrlDominio3 control =  new CtrlDominio3();
    int id;
    Date fecha;

    public VistaVerEnMente(java.awt.Frame parent, boolean modal,int id, Date fecha) {
        super(parent, modal);
        initComponents();
        this.id=id;
        this.fecha=fecha;
         cargarTemas();
        inicializarCampos(id);
       
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        checkLaboral = new javax.swing.JCheckBox();
        txtTitulo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextPane();
        comboFecha = new datechooser.beans.DateChooserCombo();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtHoras = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        boxTema = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        comboPrioridad = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        horasMax = new javax.swing.JFormattedTextField();
        horasMin = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ver EnMente");

        jLabel7.setText("Fecha");

        jLabel2.setText("Titulo");

        checkLaboral.setText("Es laboral");
        checkLaboral.setEnabled(false);

        txtTitulo.setEnabled(false);

        jLabel5.setText("Descripcion");

        txtDescripcion.setEnabled(false);
        jScrollPane2.setViewportView(txtDescripcion);

        comboFecha.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Vista En Mente");

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Num. Horas");

        txtHoras.setEnabled(false);

        jLabel6.setText("Tema");

        boxTema.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ninguno"}));
        boxTema.setEnabled(false);
        boxTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTemaActionPerformed(evt);
            }
        });

        jLabel4.setText("Prioridad");

        comboPrioridad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alta", "Media", "Baja" }));
        comboPrioridad.setEnabled(false);
        comboPrioridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPrioridadActionPerformed(evt);
            }
        });

        jLabel8.setText("Numero de horas como maximo");

        jLabel9.setText("Numero de horas como minimo");

        horasMax.setEnabled(false);
        horasMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horasMaxActionPerformed(evt);
            }
        });
        horasMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                horasMaxKeyTyped(evt);
            }
        });

        horasMin.setEnabled(false);
        horasMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                horasMinKeyTyped(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2)
                            .add(jLabel6)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel7)
                                    .add(jLabel3))
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(5, 5, 5)
                                        .add(comboFecha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                            .add(18, 18, 18)
                                            .add(txtHoras, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                            .add(18, 18, 18)
                                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                .add(boxTema, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .add(comboPrioridad, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .add(txtTitulo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))))
                            .add(checkLaboral)
                            .add(jLabel4))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                    .add(jLabel5)
                                    .add(33, 33, 33)
                                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 133, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(139, 139, 139))
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                        .add(jLabel8)
                                        .add(jLabel9))
                                    .add(18, 18, 18)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, horasMax)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, horasMin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(109, 109, 109)))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(27, 27, 27))))))
            .add(layout.createSequentialGroup()
                .add(260, 260, 260)
                .add(jLabel1)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(11, 11, 11)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(25, 25, 25)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel2)
                            .add(txtTitulo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel6)
                            .add(boxTema, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(10, 10, 10)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel4)
                            .add(comboPrioridad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(1, 1, 1)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(txtHoras, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel3))
                        .add(32, 32, 32)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel7)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, comboFecha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(45, 45, 45)
                        .add(checkLaboral))
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(32, 32, 32)
                                .add(jLabel5))
                            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(57, 57, 57)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(horasMin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel9))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(horasMax, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel8))
                        .add(32, 32, 32)
                        .add(jButton1)))
                .add(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
}//GEN-LAST:event_jButton1ActionPerformed

    private void boxTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTemaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_boxTemaActionPerformed

    private void comboPrioridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPrioridadActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_comboPrioridadActionPerformed

    private void horasMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horasMaxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_horasMaxActionPerformed

    private void horasMaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_horasMaxKeyTyped
 
}//GEN-LAST:event_horasMaxKeyTyped

    private void horasMinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_horasMinKeyTyped
        // TODO add your handling code here:

}//GEN-LAST:event_horasMinKeyTyped

    //Carga los campos de la actividad
    private void inicializarCampos(int id){
        Actividad d=control.CA3.buscarActividad(id);
        EnMente mostrador=(EnMente)d;
        Calendar c= Calendar.getInstance();

        txtTitulo.setText(mostrador.getTitulo());
        txtDescripcion.setText(mostrador.getDescripcion());
        Integer h=mostrador.getNHoras();
        txtHoras.setText(h.toString());
        checkLaboral.setSelected(mostrador.isEs_laboral());
         boxTema.setSelectedItem(control.obtenerTema(id));
        Integer hm=mostrador.getSlotMin();
        horasMin.setText(hm.toString());
        hm=mostrador.getSlotMax();
        horasMax.setText(hm.toString());
        if (fecha !=null){
        c.setTime(fecha);
        comboFecha.setSelectedDate(c);
        }
        else {comboFecha.setVisible(false);
        this.jLabel7.setVisible(false);
        }
        int p=mostrador.getPrioridad();
            if(p==1){
               comboPrioridad.setSelectedItem("Baja");
            }
            else if(p==2){
               comboPrioridad.setSelectedItem("Media");
            }
            else{
                comboPrioridad.setSelectedItem("Alta");
            }
    }

    //carga los temas en el boxTema
    private  void cargarTemas(){

        ArrayList<String>lista=control.listartemas();
        int indiceI=0;
        int tamanyo=lista.size();
        boxTema.addItem(Constantes.NINGUNO);
        while(indiceI<tamanyo){
               boxTema.addItem(lista.get(indiceI));
             indiceI++;
        }

    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            int idAct;
            Date fecha;
            public void run() {
                VistaVerEnMente dialog = new VistaVerEnMente(new javax.swing.JFrame(), true,idAct,fecha);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox boxTema;
    private javax.swing.JCheckBox checkLaboral;
    private datechooser.beans.DateChooserCombo comboFecha;
    private javax.swing.JComboBox comboPrioridad;
    private javax.swing.JFormattedTextField horasMax;
    private javax.swing.JFormattedTextField horasMin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextPane txtDescripcion;
    private javax.swing.JTextField txtHoras;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

}
