/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/* Descripcion: Permite eliminar temas creados previamente
 * interactua con CtrlDominio3
 * VistaEliminarTema.java
 * Autor: Carlos Vivas
 * Created on 12-may-2009, 10:48:02
 */

package agendainteligente;

import java.util.ArrayList;


public class VistaEliminarTema extends javax.swing.JDialog {
 static CtrlDominio2 CD3=new CtrlDominio3(); //POSTERIORMENTE MODIFICAR-----------
    /** Creates new form VistaEliminarTema */
    public VistaEliminarTema(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarTemas();
        label.setText("");
        this.setLocationRelativeTo(parent);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboTema = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        ButtonEliminar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eliminar Tema");
        setModal(true);
        setResizable(false);

        jLabel1.setText("Seleccione el tema");

        ButtonEliminar.setText("Eliminar");
        ButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel9.setText("Eliminar Tema");

        label.setForeground(new java.awt.Color(255, 0, 0));
        label.setText("jLabel2");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .add(ButtonEliminar)
                .add(36, 36, 36))
            .add(layout.createSequentialGroup()
                .add(137, 137, 137)
                .add(jLabel9)
                .addContainerGap(167, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(39, 39, 39)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(label)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(63, 63, 63)
                        .add(comboTema, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 72, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel9)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 159, Short.MAX_VALUE)
                .add(ButtonEliminar)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(89, 89, 89)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(comboTema, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 49, Short.MAX_VALUE)
                .add(label)
                .add(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarActionPerformed
        if(comboTema.getItemCount()==0){
            label.setText("No hay temas para borrar");
        }
        else{
        CD3.eliminarTema((String)comboTema.getSelectedItem());
        this.setVisible(false);
        }
}//GEN-LAST:event_ButtonEliminarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VistaEliminarTema dialog = new VistaEliminarTema(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    //Carga los temas ya creados
    private  void cargarTemas(){

        ArrayList<String>lista=CD3.listartemas();
        int indiceI=0;
        int tamanyo=lista.size();
        while(indiceI<tamanyo){
               comboTema.addItem(lista.get(indiceI));
             indiceI++;
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEliminar;
    private javax.swing.JComboBox comboTema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables

}
