/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VistaGestionTemas.java
 * Descripcion: Panel que llama a las funciones que interactuan con los temas
 * Created on 12-may-2009, 10:03:25
 * Autor: Carlos Vivas
 */

package agendainteligente;

public class VistaGestionTemas extends javax.swing.JDialog {

    /** Creates new form VistaGestionTemas */
    public VistaGestionTemas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         this.setLocationRelativeTo(parent);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        ButtonNuevoTema = new javax.swing.JButton();
        ButtonEliminarTema = new javax.swing.JButton();
        visorTemas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion Temas");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel9.setText("Gestión Temas");

        ButtonNuevoTema.setText("Crear tema nuevo");
        ButtonNuevoTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNuevoTemaActionPerformed(evt);
            }
        });

        ButtonEliminarTema.setText("Eliminar tema");
        ButtonEliminarTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarTemaActionPerformed(evt);
            }
        });

        visorTemas.setText("Visor temas-Actividades");
        visorTemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visorTemasActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(129, 129, 129)
                        .add(jLabel9))
                    .add(layout.createSequentialGroup()
                        .add(107, 107, 107)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, ButtonNuevoTema, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(ButtonEliminarTema, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(visorTemas))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(12, 12, 12)
                .add(jLabel9)
                .add(18, 18, 18)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 57, Short.MAX_VALUE)
                .add(ButtonNuevoTema)
                .add(38, 38, 38)
                .add(ButtonEliminarTema)
                .add(34, 34, 34)
                .add(visorTemas)
                .add(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonNuevoTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNuevoTemaActionPerformed
        VistaCrearTema dialog = new VistaCrearTema(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_ButtonNuevoTemaActionPerformed

    private void ButtonEliminarTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarTemaActionPerformed
         VistaEliminarTema dialog = new VistaEliminarTema(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_ButtonEliminarTemaActionPerformed

    private void visorTemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visorTemasActionPerformed
        VistaActivTemas v=new VistaActivTemas(new javax.swing.JFrame(), true);
        v.setVisible(true);
        this.dispose();
        
}//GEN-LAST:event_visorTemasActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VistaGestionTemas dialog = new VistaGestionTemas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEliminarTema;
    private javax.swing.JButton ButtonNuevoTema;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton visorTemas;
    // End of variables declaration//GEN-END:variables

}
