/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VistaEliminarCita.java
 *
 * Created on 29-abr-2009, 10:44:47
 */
package agendainteligente;

import java.util.ArrayList;
import java.util.Date;

/**
 *
 * @author Zinic
 */
public class VistaEliminarCita extends javax.swing.JDialog {

    int idActividad;
    Date fechaActualCita = null;
    CtrlAgenda CAGE = new CtrlAgenda();
    Actividad act = null;
    Cita cita = null;
    CitaRepetitiva citaRep = null;
    //CtrlDominio3 CD3=new CtrlDominio3();
    boolean esCitaRepAct = false;
    Date fechaInicioPeriodicidad;

    /** Ceates new form VistaEliminarCita */
    @SuppressWarnings({"deprecation", "deprecation", "deprecation", "deprecation", "deprecation", "deprecation", "deprecation","deprecation","deprecation","deprecation","deprecation","deprecation","deprecation","deprecation","deprecation","deprecation","deprecation"})
    public VistaEliminarCita(java.awt.Frame parent, boolean modal, int idActividad, Date fechaAct) {
        super(parent, modal);
        initComponents();
        boolean esCitaAct = false;

        this.idActividad = idActividad;
        this.fechaActualCita = (Date) fechaAct.clone();
        this.titulo.setText(CAGE.obtenerTitulo(idActividad));
        this.descripcion.setText(CAGE.obtenerDescripcionActividad(idActividad));
        act = CAGE.buscarActividad(idActividad);
        this.parametrosFranajaVisibles(false);
        this.textoError.setText("");

        if (act == null) {
            
            this.dispose();
            
        } 
        else {

            if (act.getClass().getSimpleName().equals(Constantes.CITA)) {
                
                cita = (Cita) act;
                esCitaAct = true;

            } else if (act.getClass().getSimpleName().equals(Constantes.CITAREPETITIVA)) {

                citaRep = (CitaRepetitiva) act;
                esCitaRepAct = true;

            }

            if (!esCitaAct && !esCitaRepAct) {

                this.dispose();

            } 
            else {

                ArrayList<TCtrlHorSlot> listaH = CAGE.obtenerSlotsDeActividadConFecha(idActividad, fechaAct);
                TCtrlHorSlot primero = listaH.get(0);
                TCtrlHorSlot ultimo = listaH.get(listaH.size() - 1);
                this.h1.setText(String.valueOf(primero.slot));
                this.h2.setText(String.valueOf((ultimo.slot) + 1));


                if (esCitaAct) {

                    this.textFechaFinal.setVisible(false);
                    this.fFin.setVisible(false);
                    this.radioSoloHoy.setVisible(false);
                    this.radioFranja.setVisible(false);
                    this.radioTotal.setVisible(false);
                    this.Desde.setVisible(false);
                    this.Hasta.setVisible(false);
                    this.boxFechaIni.setVisible(false);
                    this.boxFechaFin.setVisible(false);
                    this.textFechaInicial.setText("Fecha");
                    this.fIni.setText(fechaAct.getDate() + "/"
                            + (fechaAct.getMonth() + 1) + "/" + (fechaAct.getYear() + 1900));

                    if (cita.esLaboral) {
                        
                        this.boxLaboral.setSelected(true);

                    }
                } else {


                    Date fechaFin = citaRep.getFinPeriodicidad();
                    this.fFin.setText(fechaFin.getDate() +
                            "/" + (fechaFin.getMonth() + 1) + "/" + (fechaFin.getYear() + 1900));
                    Date fechaIniP = citaRep.getInicioPeriodicidad();
                    this.fechaInicioPeriodicidad = (Date) fechaIniP.clone();

                    this.fIni.setText(fechaIniP.getDate() + "/"
                            + (fechaIniP.getMonth() + 1) + "/" + (fechaIniP.getYear() + 1900));

                    if (citaRep.esLaboral) {
                        this.boxLaboral.setSelected(true);
                    }


                }


            }


        }


    }

    private void parametrosFranajaVisibles(boolean b) {

        this.Desde.setVisible(b);
        this.Hasta.setVisible(b);
        this.boxFechaIni.setVisible(b);
        this.boxFechaFin.setVisible(b);


    }

    private boolean verificarFechas(Date ini, Date fin) {

        boolean verificado = false;
        if (ini.before(fin)) {
            verificado = true;
        }
        return verificado;


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        Desde = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        radioSoloHoy = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        radioFranja = new javax.swing.JRadioButton();
        radioTotal = new javax.swing.JRadioButton();
        Hasta = new javax.swing.JLabel();
        boxFechaIni = new datechooser.beans.DateChooserCombo();
        boxFechaFin = new datechooser.beans.DateChooserCombo();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        h1 = new javax.swing.JTextField();
        h2 = new javax.swing.JTextField();
        textFechaInicial = new javax.swing.JLabel();
        textFechaFinal = new javax.swing.JLabel();
        fIni = new javax.swing.JTextField();
        fFin = new javax.swing.JTextField();
        boxLaboral = new javax.swing.JCheckBox();
        textoError = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Título");

        titulo.setEditable(false);

        Desde.setText("Desde");

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        radioSoloHoy.setText("Solo hoy");
        radioSoloHoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSoloHoyActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel10.setText("Eliminar Cita");

        radioFranja.setText("Franja");
        radioFranja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFranjaActionPerformed(evt);
            }
        });

        radioTotal.setText("Total");
        radioTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTotalActionPerformed(evt);
            }
        });

        Hasta.setText("Hasta");

        jLabel2.setText("Descripcion:");

        descripcion.setColumns(20);
        descripcion.setEditable(false);
        descripcion.setRows(5);
        jScrollPane1.setViewportView(descripcion);

        jLabel3.setText("Hora Inicio");

        jLabel4.setText("Hora Final");

        h1.setEditable(false);

        h2.setEditable(false);

        textFechaInicial.setText("fecha Inicial");

        textFechaFinal.setText("fechaFinal");

        fIni.setEditable(false);

        fFin.setEditable(false);

        boxLaboral.setText("Laboral");
        boxLaboral.setToolTipText("Seleccionado si es una cita laboral");
        boxLaboral.setEnabled(false);
        boxLaboral.setFocusable(false);

        textoError.setForeground(new java.awt.Color(255, 0, 0));
        textoError.setText("jLabel6");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 588, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(222, 222, 222)
                        .add(jLabel10))
                    .add(layout.createSequentialGroup()
                        .add(22, 22, 22)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(Hasta)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(radioSoloHoy)
                                        .add(layout.createSequentialGroup()
                                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                .add(layout.createSequentialGroup()
                                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                        .add(radioTotal)
                                                        .add(layout.createSequentialGroup()
                                                            .add(jLabel1)
                                                            .add(18, 18, 18)
                                                            .add(titulo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 124, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                        .add(radioFranja)
                                                        .add(layout.createSequentialGroup()
                                                            .add(Desde)
                                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                                            .add(textoError)))
                                                    .add(18, 18, 18)
                                                    .add(jLabel2))
                                                .add(boxLaboral))
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                                        .add(jLabel3)
                                                        .add(jButton1)
                                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                            .add(textFechaInicial)
                                                            .add(jLabel4)
                                                            .add(textFechaFinal)))
                                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                                        .add(layout.createSequentialGroup()
                                                            .add(18, 18, 18)
                                                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                                                .add(org.jdesktop.layout.GroupLayout.TRAILING, h1)
                                                                .add(org.jdesktop.layout.GroupLayout.TRAILING, h2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                                                .add(fIni, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                                                .add(fFin, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)))
                                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .add(jButton2)
                                                            .add(15, 15, 15))))))
                                        .add(boxFechaIni, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, boxFechaFin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(102, 102, 102)))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(33, 33, 33)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel1)
                            .add(titulo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel2))
                        .add(16, 16, 16)
                        .add(boxLaboral)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(radioTotal)
                        .add(3, 3, 3)
                        .add(radioSoloHoy))
                    .add(layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(radioFranja)
                    .add(h1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Desde)
                    .add(h2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4)
                    .add(textoError))
                .add(24, 24, 24)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(textFechaInicial)
                            .add(fIni, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(textFechaFinal)
                            .add(fFin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButton2)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(boxFechaIni, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(26, 26, 26)
                        .add(Hasta)
                        .add(18, 18, 18)
                        .add(boxFechaFin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioSoloHoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSoloHoyActionPerformed

        if (this.radioSoloHoy.isSelected()) {

            if (this.radioFranja.isSelected())this.radioFranja.setSelected(false);
            if (this.radioTotal.isSelected())this.radioTotal.setSelected(false);
            this.parametrosFranajaVisibles(false);


        }


}//GEN-LAST:event_radioSoloHoyActionPerformed

    private void radioFranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFranjaActionPerformed
        if (this.radioFranja.isSelected()) {

            if (this.radioSoloHoy.isSelected())this.radioSoloHoy.setSelected(false);
            if (this.radioTotal.isSelected())this.radioTotal.setSelected(false);
            this.parametrosFranajaVisibles(true);
        } else {

            this.parametrosFranajaVisibles(false);

        }

}//GEN-LAST:event_radioFranjaActionPerformed

    private void radioTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTotalActionPerformed
        // TODO add your handling code here:
        if (this.radioTotal.isSelected()) {

            if (this.radioSoloHoy.isSelected())this.radioSoloHoy.setSelected(false);
            if (this.radioFranja.isSelected())this.radioFranja.setSelected(false);
            this.parametrosFranajaVisibles(false);


        }
}//GEN-LAST:event_radioTotalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        boolean correcto = false;
//        System.out.println("imprimimos el id de actividad" + this.idActividad );
//        System.out.println("imprimimos el titulo del CAGE :  "+CAGE.obtenerTitulo(idActividad));
//        System.out.println("Es repetida segun la vista "+this.esCitaRepAct);
//        System.out.println("de todas formas imprimimos el tipo segun CAGE:  "+CAGE.buscarActividad(idActividad).getClass().getSimpleName());


        if (this.esCitaRepAct) {

            if (this.radioFranja.isSelected()) {

                Date fechaIni, fechaFin;
                fechaIni = this.boxFechaIni.getCurrent().getTime();
                fechaFin = this.boxFechaFin.getCurrent().getTime();
                if (verificarFechas(fechaIni, fechaFin)) {
                    //ponerDeNuevoFechaIniFin(this.idActividad, fechaIni, fechaFin)
                    //-->necesito buscar horario siguiente a fecha X donde este la actividad. = para inferior para la funcion
                    CAGE.eliminarActividadFranja(this.idActividad, fechaIni, fechaFin);
                    correcto = true;
                }
                else{

                    this.textoError.setText("Fechas incorrectas");
                }

            } else if (this.radioTotal.isSelected()) {

                CAGE.eliminarActividad(this.idActividad);
                correcto = true;
            } else if (this.radioSoloHoy.isSelected()) {

                CAGE.eliminarActividadDia(this.idActividad, this.fechaActualCita);
                correcto = true;
            }
        } else {
//            CAGE.listarAnadidos();
//            System.out.println("entramos aqui");
            CAGE.eliminarActividad(this.idActividad);
            CAGE.recuperarHoras(fechaActualCita, CAGE.semanaSiguiente(fechaActualCita));
            correcto = true;
        }

        if (correcto) {
            this.dispose();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            private int idAct;
            private Date fecha;

            public void run() {
                VistaEliminarCita dialog = new VistaEliminarCita(new javax.swing.JFrame(), true, idAct, fecha);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Desde;
    private javax.swing.JLabel Hasta;
    private datechooser.beans.DateChooserCombo boxFechaFin;
    private datechooser.beans.DateChooserCombo boxFechaIni;
    private javax.swing.JCheckBox boxLaboral;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JTextField fFin;
    private javax.swing.JTextField fIni;
    private javax.swing.JTextField h1;
    private javax.swing.JTextField h2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton radioFranja;
    private javax.swing.JRadioButton radioSoloHoy;
    private javax.swing.JRadioButton radioTotal;
    private javax.swing.JLabel textFechaFinal;
    private javax.swing.JLabel textFechaInicial;
    private javax.swing.JLabel textoError;
    private javax.swing.JTextField titulo;
    // End of variables declaration//GEN-END:variables
}
