/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VistaSemanaHorario.java
 *
 * Created on 18-may-2009, 2:31:46
 */

package agendainteligente;

import java.awt.Component;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Carlos Vivas Abilahoud 
 */
public class VistaSemanaHorario extends javax.swing.JPanel {

    /** Creates new form VistaSemanaHorario */
    public VistaSemanaHorario() {
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHorarios = new javax.swing.JTable();

        tablaHorarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"00", null, null, null, null, null, null, null},
                {"01", null, null, null, null, null, null, null},
                {"02", null, null, null, null, null, null, null},
                {"03", null, null, null, null, null, null, null},
                {"04", null, null, null, null, null, null, null},
                {"05", null, null, null, null, null, null, null},
                {"06", null, null, null, null, null, null, null},
                {"07", null, null, null, null, null, null, null},
                {"08", null, null, null, null, null, null, null},
                {"09", null, null, null, null, null, null, null},
                {"10", null, null, null, null, null, null, null},
                {"11", null, null, null, null, null, null, null},
                {"12", null, null, null, null, null, null, null},
                {"13", null, null, null, null, null, null, null},
                {"14", null, null, null, null, null, null, null},
                {"15", null, null, null, null, null, null, null},
                {"16", null, null, null, null, null, null, null},
                {"17", null, null, null, null, null, null, null},
                {"18", null, null, null, null, null, null, null},
                {"19", null, null, null, null, null, null, null},
                {"20", null, null, null, null, null, null, null},
                {"21", null, null, null, null, null, null, null},
                {"22", null, null, null, null, null, null, null},
                {"23", null, null, null, null, null, null, null}
            },
            new String [] {
                "Hora", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaHorarios.setToolTipText("");
        tablaHorarios.setCellSelectionEnabled(true);
        tablaHorarios.setColumnSelectionAllowed(true);
        tablaHorarios.setRowHeight(17);
        tablaHorarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaHorarios.getTableHeader().setReorderingAllowed(false);
        tablaHorarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaHorariosMouseClicked(evt);
            }
        });
        tablaHorarios.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tablaHorariosMouseMoved(evt);
            }
        });
        jScrollPane1.setViewportView(tablaHorarios);
        tablaHorarios.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

//    private Date obtenerFechaDiaSeleccionado(Date d, int columna) {
//
//        Date temp = new Date();
//        temp = (Date) d.clone();
//        for (int i =0;i<(columna-1);i++) temp =CtrlDominio3.diaSiguiente(temp);
//        return temp;
//
//    }



    private void tablaHorariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaHorariosMouseClicked

       
        int columna,fila;
        columna = this.tablaHorarios.getSelectedColumn();
        fila= this.tablaHorarios.getSelectedRow();

        Date fechaActual = CD3.obtenerFechaDiaSeleccionado(this.fechaInicioSemana, columna);
        int id=CD3.obtenerIdActividad(fila, columna-1, CD3.getSemanaHorario());


        VistaGestionActividad d = new VistaGestionActividad(new javax.swing.JFrame(),true,id,fechaActual);
           d.setVisible(true);
    }//GEN-LAST:event_tablaHorariosMouseClicked

    private void tablaHorariosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaHorariosMouseMoved

    }//GEN-LAST:event_tablaHorariosMouseMoved

     CtrlDominio3 CD3 = new CtrlDominio3();
    public Date fechaInicioSemana = new Date();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tablaHorarios;
    // End of variables declaration//GEN-END:variables

}
