/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VistaDiaHorario.java
 *
 * Created on 18-may-2009, 13:15:05
 */

package agendainteligente;

import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author Carlos Vivas Abilahoud 
 */

public class VistaDiaHorario extends javax.swing.JPanel {

    /** Creates new form VistaDiaHorario */
    public VistaDiaHorario() {
        initComponents();
        Date d = new Date();
        int dia=d.getDay();
        if (dia==1){
        tablaHorarios.getColumnModel().getColumn(1).setHeaderValue("lunes hoy");
        }
    }

    public void indicarDiaCabecera(){
    
        String diaAct = "Dia Seleccionado";
        
        tablaHorarios.getColumnModel().getColumn(1).setHeaderValue(diaAct);
    
    
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHorarios = new javax.swing.JTable();

        tablaHorarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"00", null},
                {"01", null},
                {"02", null},
                {"03", null},
                {"04", null},
                {"05", null},
                {"06", null},
                {"07", null},
                {"08", null},
                {"09", null},
                {"10", null},
                {"11", null},
                {"12", null},
                {"13", null},
                {"14", null},
                {"15", null},
                {"16", null},
                {"17", null},
                {"18", null},
                {"19", null},
                {"20", null},
                {"21", null},
                {"22", null},
                {"23", null}
            },
            new String [] {
                "Hora", "Lunes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaHorarios.setCellSelectionEnabled(true);
        tablaHorarios.setRowHeight(17);
        tablaHorarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaHorarios.getTableHeader().setReorderingAllowed(false);
        tablaHorarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaHorariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaHorarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tablaHorariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaHorariosMouseClicked
        CtrlVistaPrincipal CVP = new CtrlVistaPrincipal();
        int columna,fila;
        fila= this.tablaHorarios.getSelectedRow();

        int id=CVP.obtenerIdActividad(fila, CVP.getDiaHorario());
        Date fecha=CVP.getDiaIndicadoActualmente();
        VistaGestionActividad d = new VistaGestionActividad(new javax.swing.JFrame(),true,id,fecha);
           d.setVisible(true);
    }//GEN-LAST:event_tablaHorariosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tablaHorarios;
    // End of variables declaration//GEN-END:variables

}
