/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/* Descripcion: Muestra las actividades asociadas a cada tema.
 * VistaActivTemas.java
 * Autor Carlos Vivas
 * Created on 26-may-2009, 23:05:45
 */

package agendainteligente;

import java.util.ArrayList;
import java.util.Hashtable;


public class VistaActivTemas extends javax.swing.JDialog {

    CtrlDominio3 CD3=new CtrlDominio3();
    ArrayList<Integer>ids=new ArrayList<Integer>();

    public VistaActivTemas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        cargarTemas();
        inicializarCampos();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        comboTema = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        lista = new java.awt.List();
        buttonElim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Visor temas Actividades");

        jLabel5.setText("Seleccione el tema");

        comboTema.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));
        comboTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTemaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel9.setText("Visor temas-Actividades");

        lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaMouseClicked(evt);
            }
        });

        buttonElim.setText("Eliminar actividades asociadas");
        buttonElim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonElimActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(83, 83, 83)
                        .add(jLabel5)
                        .add(47, 47, 47)
                        .add(comboTema, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(153, 153, 153)
                        .add(lista, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(129, 129, 129)
                        .add(jLabel9)))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(261, Short.MAX_VALUE)
                .add(buttonElim)
                .add(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(26, 26, 26)
                .add(jLabel9)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(47, 47, 47)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(comboTema, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(32, 32, 32)
                .add(lista, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 117, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 60, Short.MAX_VALUE)
                .add(buttonElim)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTemaActionPerformed
        inicializarCampos();
    }//GEN-LAST:event_comboTemaActionPerformed

    private void listaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaMouseClicked

    }//GEN-LAST:event_listaMouseClicked

    private void buttonElimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonElimActionPerformed
            int tam=ids.size();
            int indiceI=0;

            while(indiceI<tam){

                CD3.eliminarActividad(ids.get(indiceI));
                indiceI++;
            }
            inicializarCampos();
        
    }//GEN-LAST:event_buttonElimActionPerformed

    /*Carga todos los temas en el desplegable*/
    private  void cargarTemas(){

        ArrayList<String>lista=CD3.listartemas();
        int indiceI=0;
        int tamanyo=lista.size();
        comboTema.addItem(Constantes.NINGUNO);
        while(indiceI<tamanyo){
               comboTema.addItem(lista.get(indiceI));
             indiceI++;
        }

    }

    //Inicializa el contenido a mostrar
    private void inicializarCampos(){

        lista.removeAll();
        ArrayList<String>la=seleccionaAct();
        int tam=la.size();
        int indiceI=0;

        while(indiceI<tam){
            lista.add(la.get(indiceI));
            indiceI++;
        }
        
    }

    //Muestra las actividades asociadas a cada tema
    private ArrayList<String> seleccionaAct(){

       Hashtable t=CD3.CA2.getCtrlActividad2();
       int numAct=CD3.CA3.getIndiceActividad();
       int indiceI=1;
       TCtrlAct2 temp=new TCtrlAct2();
       ids.clear();

       ArrayList<String>la=new ArrayList<String>();
       String temaSelected=(String)comboTema.getSelectedItem();

       if(!temaSelected.equals(Constantes.NINGUNO)){
          while(indiceI<=numAct){
             temp=(TCtrlAct2)t.get(indiceI);
             if(temp!=null && !temp.arrayTema.isEmpty() && temp.arrayTema.get(0).getNom().equals(temaSelected)){
                 Actividad a=CD3.buscarActividad(indiceI);
                 if (a!=null){
                       la.add(a.getTitulo());
                       ids.add(indiceI);
                 }//fin if          
             }//fin if
             indiceI++;
          } //fin while
          
       }//fin if

        return la;
       
    }


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VistaActivTemas dialog = new VistaActivTemas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonElim;
    private static javax.swing.JComboBox comboTema;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.List lista;
    // End of variables declaration//GEN-END:variables

}
