/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * vistaModificarCita.java
 *
 * Created on 29-may-2009, 11:28:48
 */

package agendainteligente;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author carlos
 */
public class VistaModificarCita extends javax.swing.JDialog {
    CtrlDominio3 CD3=new CtrlDominio3(); //------------------PRUEBAS LUEGO BORRAR
    CtrlAgenda CAGE = new CtrlAgenda();
    int idActividad;
    String tipo;
    boolean esCitaRepAct = false;
    Cita cita= null;
    CitaRepetitiva citaRep = null;
    Date fechaActual;
    boolean teniaAviso = false;
    boolean eraLaboral = false;
    int hInicioPrevia =0;
    int hFinPrevia = 0;
    boolean teniaTema;

    /** Creates new form VistaModificarCita */
    public VistaModificarCita(java.awt.Frame parent, boolean modal,int id,Date fechaAct) {
        super(parent, modal);
        initComponents();
        cargarTemas();
        boolean esCitaAct=false;
        textoErrorTitulo.setText("");
        textoErrorDescripcion.setText("");
        textoErrorHorai.setText("");
        textoErrorHoraf.setText("");
        textoErrorRep.setText("");
        textoErrorTema.setText("");
        textoErrorFechaRep.setText("");
        dateComboRep.setVisible(false);
        FinRep.setVisible(false);
        this.idActividad=id;
        Actividad act = CAGE.buscarActividad(idActividad);
        Calendar tempcal= Calendar.getInstance();
        tempcal.setTime(fechaAct);
        this.dateComboIni.setSelectedDate(tempcal);

        if (act==null) this.dispose();
        else {
            if (CAGE.tieneAviso(idActividad, fechaAct)) {
                this.boxAviso.setSelected(true);
                this.teniaAviso=true;
            }
            if (!CAGE.obtenerTema(idActividad).equals(Constantes.NINGUNO)) {
                this.boxTema.setSelectedItem(CAGE.obtenerTema(idActividad));
                this.teniaTema=true;

            }

            if (act.getClass().getSimpleName().equals(Constantes.CITA)) {

                cita = (Cita) act;
                esCitaAct = true;

            } else if (act.getClass().getSimpleName().equals(Constantes.CITAREPETITIVA)) {

                citaRep = (CitaRepetitiva) act;
                esCitaRepAct = true;

            }

            if (!esCitaAct && !esCitaRepAct) {

                this.dispose();

            }
            else{
                ArrayList<TCtrlHorSlot> listaH = CAGE.obtenerSlotsDeActividadConFecha(this.idActividad, fechaAct);
                TCtrlHorSlot primero = listaH.get(0);
                TCtrlHorSlot ultimo = listaH.get(listaH.size() - 1);
                this.hInicioPrevia = primero.slot;
                this.hFinPrevia= ultimo.slot+1;
                this.boxHoraIni.setSelectedItem(String.valueOf(primero.slot));
                this.boxHoraFin.setSelectedItem(String.valueOf((ultimo.slot) + 1));
                this.texTitulo.setText(CAGE.obtenerTitulo(idActividad));
                this.jTextArea1.setText(CAGE.obtenerDescripcionActividad(idActividad));




                if (esCitaAct){

                    if (cita.isEsLaboral()) {
                        this.radioLab.setSelected(true);
                        this.eraLaboral=true;
                    }



                }
                else {
                    this.radioRep.setEnabled(false);
                    this.radioRep.setSelected(true);
                        if (citaRep.isEsLaboral()) {
                        this.radioLab.setSelected(true);
                        this.eraLaboral=true;
                    }
                    this.boxPeriodicidad.setSelectedIndex(citaRep.getPeriodicidad());
                    dateComboRep.setVisible(true);
                    FinRep.setVisible(true);
                    Calendar tempcal2=Calendar.getInstance();
                    tempcal2.setTime(citaRep.getFinPeriodicidad());
                    dateComboRep.setSelectedDate(tempcal2);





                }



            }




        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        radioRep = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        boxTema = new javax.swing.JComboBox();
        texTitulo = new javax.swing.JTextField();
        textoErrorTitulo = new javax.swing.JLabel();
        creaTema = new javax.swing.JButton();
        textoErrorDescripcion = new javax.swing.JLabel();
        textoErrorTema = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        boxPeriodicidad = new javax.swing.JComboBox();
        textoErrorRep = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        botonAcceptar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        FinRep = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        boxAviso = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        textoErrorHorai = new javax.swing.JLabel();
        textoErrorHoraf = new javax.swing.JLabel();
        dateComboIni = new datechooser.beans.DateChooserCombo();
        boxHoraIni = new javax.swing.JComboBox();
        boxHoraFin = new javax.swing.JComboBox();
        dateComboRep = new datechooser.beans.DateChooserCombo();
        textoErrorFechaRep = new javax.swing.JLabel();
        radioLab = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel10.setText("Crear Cita");

        radioRep.setText("Repetitiva");
        radioRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRepActionPerformed(evt);
            }
        });

        jLabel3.setText("Tema");

        jLabel2.setText("Descripción");

        jLabel1.setText("Título");

        boxTema.setModel(new javax.swing.DefaultComboBoxModel());

        texTitulo.setToolTipText("inserte texto");
        texTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texTituloActionPerformed(evt);
            }
        });

        textoErrorTitulo.setForeground(new java.awt.Color(255, 0, 0));
        textoErrorTitulo.setText("jLabel8");

        creaTema.setText("Crear Tema");
        creaTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creaTemaActionPerformed(evt);
            }
        });

        textoErrorDescripcion.setForeground(new java.awt.Color(255, 0, 0));
        textoErrorDescripcion.setText("jLabel12");

        textoErrorTema.setForeground(new java.awt.Color(255, 0, 0));
        textoErrorTema.setText("jLabel8");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        boxPeriodicidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ninguna", "Diaria", "Semanal", "Mensual", "Anual" }));
        boxPeriodicidad.setToolTipText("indique la periodicidad");
        boxPeriodicidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxPeriodicidadActionPerformed(evt);
            }
        });

        textoErrorRep.setForeground(new java.awt.Color(255, 0, 0));
        textoErrorRep.setText("jLabel8");

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        botonAcceptar.setText("Aceptar");
        botonAcceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAcceptarActionPerformed(evt);
            }
        });

        jLabel6.setText("Hora inicio");

        FinRep.setText("Fecha Fin");

        jLabel7.setText("Hora fin");

        boxAviso.setText("Aviso");

        jLabel5.setText("Fecha ");

        textoErrorHorai.setForeground(new java.awt.Color(255, 0, 0));
        textoErrorHorai.setText("jLabel14");

        textoErrorHoraf.setForeground(new java.awt.Color(255, 0, 0));
        textoErrorHoraf.setText("jLabel8");

        boxHoraIni.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3","4", "5", "6", "7","8", "9", "10", "11","12", "13", "14", "15","16", "17", "18", "19","20", "21", "22", "23" }));

        boxHoraFin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3","4", "5", "6", "7","8", "9", "10", "11","12", "13", "14", "15","16", "17", "18", "19","20", "21", "22", "23","24" }));

        textoErrorFechaRep.setForeground(new java.awt.Color(255, 0, 0));
        textoErrorFechaRep.setText("jLabel8");

        radioLab.setText("Laboral");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(387, Short.MAX_VALUE)
                .addComponent(textoErrorHorai)
                .addGap(240, 240, 240))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(textoErrorDescripcion)
                .addContainerGap(578, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(287, 287, 287)
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(radioRep)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel1))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(boxTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(texTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(textoErrorTitulo)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                            .addComponent(creaTema)
                                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                                                                .addComponent(textoErrorTema)
                                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(21, 21, 21)
                                                            .addComponent(boxPeriodicidad, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(8, 8, 8)
                                                    .addComponent(textoErrorRep, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(58, 58, 58))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(cancelar)
                                            .addGap(18, 18, 18)
                                            .addComponent(botonAcceptar)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(FinRep)
                                        .addComponent(jLabel7)
                                        .addComponent(boxAviso)
                                        .addComponent(jLabel5)
                                        .addComponent(textoErrorHoraf))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(dateComboIni, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(boxHoraIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(boxHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(15, 15, 15))
                                        .addComponent(dateComboRep, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                        .addComponent(textoErrorFechaRep, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(66, 66, 66))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(radioLab)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 496, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(textoErrorDescripcion)
                .addGap(18, 18, 18)
                .addComponent(textoErrorHorai)
                .addContainerGap(290, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(6, 6, 6))
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(creaTema)
                                        .addComponent(jLabel3)
                                        .addComponent(boxTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(boxAviso)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(dateComboIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(15, 15, 15))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(texTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(textoErrorTitulo)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel1))
                                            .addGap(14, 14, 14)))
                                    .addGap(30, 30, 30)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(boxHoraIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(boxHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(20, 20, 20)
                                    .addComponent(textoErrorHoraf)
                                    .addGap(49, 49, 49)))
                            .addGap(0, 0, 0)
                            .addComponent(textoErrorTema)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(73, 73, 73)
                                    .addComponent(FinRep))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(72, 72, 72)
                                    .addComponent(dateComboRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textoErrorFechaRep)
                                    .addGap(9, 9, 9)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cancelar)
                                        .addComponent(botonAcceptar)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(241, 241, 241)
                            .addComponent(radioLab)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(radioRep)
                                .addComponent(boxPeriodicidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(textoErrorRep, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(27, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRepActionPerformed


        if (radioRep.isSelected()){
            dateComboRep.setVisible(true);
            FinRep.setVisible(true);
        }

        else {
            dateComboRep.setVisible(false);
            FinRep.setVisible(false);
        }
}//GEN-LAST:event_radioRepActionPerformed

    private void texTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texTituloActionPerformed
         textoErrorTitulo.setText("");
        // TODO add your handling code here:
}//GEN-LAST:event_texTituloActionPerformed

    private void creaTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creaTemaActionPerformed
        VistaCrearTema nuevoTema = new VistaCrearTema(new javax.swing.JFrame(), true);
        nuevoTema.setVisible(true);
        boxTema.removeAllItems();
        cargarTemas();
}//GEN-LAST:event_creaTemaActionPerformed

    private void boxPeriodicidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxPeriodicidadActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_boxPeriodicidadActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.dispose();        // TODO add your handling code here:
}//GEN-LAST:event_cancelarActionPerformed

    private void botonAcceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAcceptarActionPerformed
         /*Comprobamos que todos los datos dean correctos, y en el caso de serlo creamos la cita*/

        int hIni = -1;
        int hFin = -1;
        boolean correcto=true;
        boolean laboral = radioLab.isSelected();
        boolean reps = radioRep.isSelected();
        boolean aviso = boxAviso.isSelected();
        String period=null;
        String titulo = null;
        String desc = null;
        String tema=null;
        Date fecha1=null;
        Date fecha2=null;
        Calendar fechaTemp1 = null;
        Calendar fechaTemp2 = null;
        int valorPeriodicidad=Constantes.INCORRECTO;
        int idAct=0;
        boolean creado= false;

        if (boxHoraIni.getSelectedItem()==null || boxHoraFin.getSelectedItem()==null  ) {
            textoErrorHorai.setText(Constantes.INTROHORA);
            correcto = false;}


        else{
            /*comprobamos parametros de entrada*/
            //            System.out.println("pasamos por el primer else");
            hIni=Integer.parseInt((String)boxHoraIni.getSelectedItem());
            hFin=Integer.parseInt((String)boxHoraFin.getSelectedItem());
            period = (String)boxPeriodicidad.getSelectedItem();
            valorPeriodicidad = this.obtenerPeriodicidad(period);
            titulo= texTitulo.getText();
            desc = jTextArea1.getText();
            tema = (String)boxTema.getSelectedItem();
            fechaTemp1 = dateComboIni.getCurrent();
            fecha1 = fechaTemp1.getTime();
            correcto = comprobarValores(hIni, hFin,reps,valorPeriodicidad,titulo,desc);

        }

        if (correcto){
            /*parametros de entrada correctos: pasamos a insertar la actividad
             * necesidad vigilar citas con slots superpuestos.SOBRETODO repetitivas
             */
            CtrlCrearActividad2 CCA2= new CtrlCrearActividad2();
            CtrlCrearTema CCT = new CtrlCrearTema();
            //            System.out.println("correcto por ahora a crear actividad");
            if (reps){
                //                System.out.println("es repetitiva");
                CAGE.eliminarActividad(this.idActividad);
                fechaTemp2 = dateComboRep.getCurrent();
                fecha2 = fechaTemp2.getTime();
                int test = comprobarFecha(fechaTemp1,fechaTemp2);

                if (test ==0 ){

                    idAct=CCA2.crearActividad(titulo, desc, Constantes.CITAREPETITIVA);
                    CCA2.completarCitaRepetitiva(laboral, valorPeriodicidad, fecha1,fecha2);
                    creado = true;
                    //                    CD3.listarAnadidos();
                    //insertar horarios
                } else if (test ==1){
                    this.textoErrorFechaRep.setText("La fecha ha de ser posterior a la fecha actual");
                } else{
                    this.textoErrorHoraf.setText("Solo se gestionan 10 años maximo");
                }

            } else{
                //                System.out.println("no repetitiva");
                CAGE.eliminarActividad(this.idActividad);
                idAct=CCA2.crearActividad(titulo, desc, Constantes.CITA);
                CCA2.completarCita(reps, laboral);
                creado = true;
                //                CD3.listarAnadidos();
                //insertar horarios

            }

            if (creado){
                //                System.out.println("Se ha creado la cita");
                /*Pasamos a insertar horarios de la cita*/

                if (!tema.equals(Constantes.NINGUNO) && !tema.equals("")) CCT.crearTema(tema, titulo, idAct);
                int insercionCorrecta=-1;
                if (reps){

                    CAGE.insertarPeriodicamente(idAct,fecha1,fecha2,hIni,hFin,valorPeriodicidad,aviso);
                } else{


                    insercionCorrecta=CAGE.asignarNuevoHorarioCita(idAct, fecha1, hIni, hFin);


                    if (insercionCorrecta>0){
                        CtrlEliminarActividad CEA= new CtrlEliminarActividad();
                        CEA.eliminarActividadTodo(idAct);

                    }
                }
                if (aviso){

                    CtrlCrearAviso CCA =  new CtrlCrearAviso();
                    CCA.crearAviso(fecha1, idAct);

                }

                this.dispose();
            }




        }





    }//GEN-LAST:event_botonAcceptarActionPerformed


        private  void cargarTemas(){

        @SuppressWarnings("unchecked")
        ArrayList<String>lista=CD3.listartemas();
        int indiceI=0;
        int tamanyo=lista.size();
        boxTema.addItem(Constantes.NINGUNO);
        while(indiceI<tamanyo){
               boxTema.addItem(lista.get(indiceI));
             indiceI++;
        }

    }
    public boolean comprobarValores(int hInicio, int hFin, boolean rep,
            int period,String titulo, String descripcion){

        boolean correcto = true;


        textoErrorTitulo.setText("");
        textoErrorDescripcion.setText("");
        textoErrorHorai.setText("");
        textoErrorHoraf.setText("");
        textoErrorRep.setText("");
        textoErrorTema.setText("");
        textoErrorFechaRep.setText("");



        if (hInicio>=hFin) {
            textoErrorHorai.setText(Constantes.ERRORFORMATO);
            correcto=false;
        }

        if (hInicio<0 || hInicio>23) {
            textoErrorHorai.setText(Constantes.HORAINCORRECTA);
            correcto=false;
        }
        if (hFin<0 || hInicio>23) {
            textoErrorHoraf.setText(Constantes.HORAINCORRECTA);
            correcto=false;}

        if (rep && period<0){

            textoErrorRep.setText("Introduce una periodicidad");
            correcto=false;
        }

//        if (rep && (this.obtenerPeriodicidad(period)<0)){
//
//            textoErrorRep.setText("Error en la periodicidad");
//            correcto=false;
//
//        }

        if (titulo.isEmpty() || titulo.equals("")) {

            textoErrorTitulo.setText("Itroduce un titulo valido");
            correcto=false;
        }
        if (descripcion.isEmpty() || descripcion.equals("")) {

            textoErrorDescripcion.setText("Itroduce una descripcion valida");
            correcto=false;
        }


    return correcto;
    }

     private int comprobarFecha(Calendar fechaTemp1, Calendar fechaTemp2) {

         int correct = 0;
         if (fechaTemp1.after(fechaTemp2)) correct = 1;
         if (fechaTemp1.get(Calendar.YEAR)+10 < fechaTemp2.get(Calendar.YEAR)) correct = 2;
         return correct;

    }

     private int obtenerPeriodicidad (String periodo){

         periodo.trim();
         int periodicidad = Constantes.INCORRECTO;
         if (periodo.equals("Diaria")) periodicidad= Constantes.DIARIA;
         if (periodo.equals("Semanal"))periodicidad=  Constantes.SEMANAL;
         if (periodo.equals("Mensual"))periodicidad=  Constantes.MENSUAL;
         if (periodo.equals("Anual"))periodicidad=  Constantes.ANUAL;

         return periodicidad;
     }



    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            private int idAct;
            private Date fecha;
            public void run() {
                VistaModificarCita dialog = new VistaModificarCita(new javax.swing.JFrame(), true,idAct,fecha);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FinRep;
    private javax.swing.JButton botonAcceptar;
    private javax.swing.JCheckBox boxAviso;
    private javax.swing.JComboBox boxHoraFin;
    private javax.swing.JComboBox boxHoraIni;
    private javax.swing.JComboBox boxPeriodicidad;
    protected javax.swing.JComboBox boxTema;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton creaTema;
    private datechooser.beans.DateChooserCombo dateComboIni;
    private datechooser.beans.DateChooserCombo dateComboRep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton radioLab;
    private javax.swing.JRadioButton radioRep;
    protected javax.swing.JTextField texTitulo;
    private javax.swing.JLabel textoErrorDescripcion;
    private javax.swing.JLabel textoErrorFechaRep;
    private javax.swing.JLabel textoErrorHoraf;
    private javax.swing.JLabel textoErrorHorai;
    private javax.swing.JLabel textoErrorRep;
    private javax.swing.JLabel textoErrorTema;
    private javax.swing.JLabel textoErrorTitulo;
    // End of variables declaration//GEN-END:variables

}
